const QuestionDetailsActionTypes = {
  FETCH_QUESTIONDETAILS_START: "FETCH_QUESTIONDETAILS_START",
  FETCH_QUESTIONDETAILS_SUCCESS: "FETCH_QUESTIONDETAILS_SUCCESS",
  FETCH_QUESTIONDETAILS_FAILURE: "FETCH_QUESTIONDETAILS_FAILURE",
  PLACE_VOTE_START: "PLACE_VOTE_START",
  PLACE_VOTE_SUCCESS: "PLACE_VOTE_SUCCESS",
  PLACE_VOTE_FAILURE: "PLACE_VOTE_FAILURE"
};

export default QuestionDetailsActionTypes;
