const QuestionDetailsActionTypes = {
  FETCH_QUESTIONDETAILS_START: "FETCH_QUESTIONDETAILS_START",
  FETCH_QUESTIONDETAILS_SUCCESS: "FETCH_QUESTIONDETAILS_SUCCESS",
  FETCH_QUESTIONDETAILS_FAILURE: "FETCH_QUESTIONDETAILS_FAILURE"
};

export default QuestionDetailsActionTypes;
