const QuestionsListActionTypes = {
  FETCH_QUESTIONSLIST_START: "FETCH_QUESTIONSLIST_START",
  FETCH_QUESTIONSLIST_SUCCESS: "FETCH_QUESTIONSLIST_SUCCESS",
  FETCH_QUESTIONSLIST_FAILURE: "FETCH_QUESTIONSLIST_FAILURE",
  ADD_NEW_QUESTION_START: "ADD_NEW_QUESTION_START",
  ADD_NEW_QUESTION_SUCCESS: "ADD_NEW_QUESTION_SUCCESS",
  ADD_NEW_QUESTION_FAILURE: "ADD_NEW_QUESTION_FAILURE",
  MESSAGE_HIDE: "MESSAGE_HIDE"
};

export default QuestionsListActionTypes;
