const QuestionsListActionTypes = {
  FETCH_QUESTIONSLIST_START: "FETCH_QUESTIONSLIST_START",
  FETCH_QUESTIONSLIST_SUCCESS: "FETCH_QUESTIONSLIST_SUCCESS",
  FETCH_QUESTIONSLIST_FAILURE: "FETCH_QUESTIONSLIST_FAILURE"
};

export default QuestionsListActionTypes;
